receivers:
  otlp: 
    protocols:
      http:
        endpoint: 'http://localhost:3000/v1/traces'

processors:
  batch:
    timeout: 10s
    send_batch_size: 10000
    send_batch_max_size: 11000

exporters:
  otlp:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
